var PORT, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../.');

support = require('./support');

PORT = 0;

describe('model.special.name', function() {
  return describe('use function keyword', function() {
    before(function(done) {
      var conn, s, server;
      conn = 'mongodb://localhost/odata-test';
      server = odata(conn);
      server.resource('funcion-keyword', {
        year: Number
      });
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return done();
      });
    });
    return it('should work', function(done) {
      return request("http://localhost:" + PORT).post('/funcion-keyword').send({
        year: 2015
      }).expect(201, done);
    });
  });
});

// ---
// generated by coffee-script 1.9.2
