var PORT, bookSchema, books, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../.');

support = require('./support');

PORT = 0;

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

books = void 0;

describe('odata.query.count', function() {
  before(function(done) {
    var conn, server;
    conn = 'mongodb://localhost/odata-test';
    server = odata(conn);
    server.resource('book', bookSchema);
    return support(conn, function(data) {
      var s;
      books = data;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return done();
      });
    });
  });
  it('should get count', function(done) {
    return request("http://localhost:" + PORT).get("/book?$count=true").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.should.be.have.property('@odata.count');
      res.body.should.be.have.property('value');
      res.body['@odata.count'].should.be.equal(res.body.value.length);
      return done();
    });
  });
  it('should not get count', function(done) {
    return request("http://localhost:" + PORT).get("/book?$count=false").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.should.be.not.have.property('@odata.count');
      return done();
    });
  });
  return it('should 500 when $count isn\'t \'true\' or \'false\'', function(done) {
    return request("http://localhost:" + PORT).get("/book?$count=1").expect(500, done);
  });
});

// ---
// generated by coffee-script 1.9.2
