var PORT, bookSchema, books, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../.');

support = require('./support');

PORT = 0;

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

books = void 0;

describe('odata.query.select', function() {
  before(function(done) {
    var conn, server;
    conn = 'mongodb://localhost/odata-test';
    server = odata(conn);
    server.resource('book', bookSchema);
    return support(conn, function(data) {
      var s;
      books = data;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return done();
      });
    });
  });
  it('should select anyone field', function(done) {
    return request("http://localhost:" + PORT).get("/book?$select=price").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.value[0].should.be.have.property('price');
      res.body.value[0].should.be.not.have.property('title');
      res.body.value[0].should.be.not.have.property('id');
      return done();
    });
  });
  it('should select multiple field', function(done) {
    return request("http://localhost:" + PORT).get("/book?$select=price,title").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.value[0].should.be.have.property('price');
      res.body.value[0].should.be.have.property('title');
      res.body.value[0].should.be.not.have.property('id');
      return done();
    });
  });
  it('should select multiple field with blank space', function(done) {
    return request("http://localhost:" + PORT).get("/book?$select=price,   title").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.value[0].should.be.have.property('price');
      res.body.value[0].should.be.have.property('title');
      return done();
    });
  });
  it('should select id field', function(done) {
    return request("http://localhost:" + PORT).get("/book?$select=price,title,id").expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.value[0].should.be.have.property('price');
      res.body.value[0].should.be.have.property('title');
      res.body.value[0].should.be.have.property('id');
      return done();
    });
  });
  return it('should ignore when select not exist field', function(done) {
    return request("http://localhost:" + PORT).get("/book?$select=not-exist-field").expect(200, done);
  });
});

// ---
// generated by coffee-script 1.9.2
