var bookSchema, books, conn, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../.');

support = require('./support');

bookSchema = {
  title: String
};

conn = 'mongodb://localhost/odata-test';

books = void 0;

describe('options.prefix', function() {
  it('should be 200 when use SET', function(done) {
    var PORT, s, server;
    PORT = 0;
    server = odata(conn);
    server.set('prefix', '/api');
    server.resource('book', bookSchema);
    return s = server.listen(PORT, function() {
      PORT = s.address().port;
      return request("http://localhost:" + PORT).get("/api/book").expect(200, done);
    });
  });
  it('should be 200 when do not add `/`', function(done) {
    var PORT, s, server;
    PORT = 0;
    server = odata(conn);
    server.set('prefix', 'api');
    server.resource('book', bookSchema);
    return s = server.listen(PORT, function() {
      PORT = s.address().port;
      return request("http://localhost:" + PORT).get("/api/book").expect(200, done);
    });
  });
  return it('should be 200 when set it at init function', function(done) {
    var PORT, s, server;
    PORT = 0;
    server = odata(conn, '/api');
    server.resource('book', bookSchema);
    return s = server.listen(PORT, function() {
      PORT = s.address().port;
      return request("http://localhost:" + PORT).get("/api/book").expect(200, done);
    });
  });
});

// ---
// generated by coffee-script 1.9.2
