var PORT, bookSchema, books, odata, request, should, support, uuid;

should = require('should');

request = require('supertest');

uuid = require('node-uuid');

odata = require('../.');

support = require('./support');

PORT = 0;

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

books = void 0;

describe('rest.put', function() {
  before(function(done) {
    var conn, server;
    conn = 'mongodb://localhost/odata-test';
    server = odata(conn);
    server.resource('book', bookSchema);
    return support(conn, function(data) {
      var s;
      books = data;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return done();
      });
    });
  });
  it('should modify resource', function(done) {
    books[0].title = 'modify title';
    return request("http://localhost:" + PORT).put("/book(" + books[0].id + ")").send(books[0]).expect(200).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.should.be.have.property('title');
      res.body.title.should.be.equal(books[0].title);
      return done();
    });
  });
  it('should create resource if with a new id', function(done) {
    var id, title;
    id = uuid.v4();
    title = 'new title';
    return request("http://localhost:" + PORT).put("/book(" + id + ")").send({
      title: title
    }).expect(201).end(function(err, res) {
      if (err) {
        return done(err);
      }
      res.body.should.be.have.property('title');
      res.body.title.should.be.equal(title);
      res.body.should.be.have.property('id');
      res.body.id.should.be.equal(id);
      return done();
    });
  });
  it('should be 404 if without id', function(done) {
    return request("http://localhost:" + PORT).put("/book").send(books[0]).expect(404, done);
  });
  return it("should 400 if with a wrong id", function(done) {
    return request("http://localhost:" + PORT).put("/book(wrong-id)").send(books[0]).expect(400, done);
  });
});

// ---
// generated by coffee-script 1.9.2
