var PORT, bookSchema, books, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../.');

support = require('./support');

PORT = 0;

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

books = void 0;

describe('rest.delete', function() {
  before(function(done) {
    var conn, server;
    conn = 'mongodb://localhost/odata-test';
    server = odata(conn);
    server.resource('book', bookSchema);
    return support(conn, function(data) {
      var s;
      books = data;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return done();
      });
    });
  });
  it('should delete resource if it exist', function(done) {
    return request("http://localhost:" + PORT).del("/book(" + books[0].id + ")").expect(200, done);
  });
  it('should be 404 if resource not exist', function(done) {
    return request("http://localhost:" + PORT).del("/book(00000)").expect(404, done);
  });
  it('should be 404 if without id', function(done) {
    return request("http://localhost:" + PORT).del("/book").expect(404, done);
  });
  return it('should 404 if try to delete a resource twice', function(done) {
    return request("http://localhost:" + PORT).del("/book/" + books[1].id).end(function(err, res) {
      return request("http://localhost:" + PORT).del("/odata(book/" + books[1].id + ")").expect(404, done);
    });
  });
});

// ---
// generated by coffee-script 1.9.2
