var should, utils;

should = require('should');

utils = require('../lib/utils');

describe('min', function() {
  return it('should work', function(done) {
    utils.min([1, 10, 100]).should.be.equal(1);
    utils.min([100, 10, 1]).should.be.equal(1);
    utils.min([-1, 0, 1]).should.be.equal(-1);
    utils.min([1, 0, -1]).should.be.equal(-1);
    utils.min([5, 0, -5, 10, -10]).should.be.equal(-10);
    utils.min([1, void 0]).should.be.equal(1);
    utils.min([void 0, 1]).should.be.equal(1);
    utils.min([1, 'a']).should.be.equal(1);
    utils.min(['a', 1]).should.be.equal(1);
    utils.min([1, 1]).should.be.equal(1);
    return done();
  });
});

describe('split', function() {
  it('should work with one keyword', function(done) {
    var result;
    result = utils.split("title eq 'something' and price gt 10", 'and');
    result[0].should.be.equal("title eq 'something'");
    result[1].should.be.equal("and");
    result[2].should.be.equal("price gt 10");
    return done();
  });
  it('should work with one keyword(array)', function(done) {
    var result;
    result = utils.split("title eq 'something' and price gt 10", ['and']);
    result[0].should.be.equal("title eq 'something'");
    result[1].should.be.equal("and");
    result[2].should.be.equal("price gt 10");
    return done();
  });
  return it('should work with multiple keywords', function(done) {
    var result;
    result = utils.split("title eq 'something' and price gt 10 or author eq 'somebody'", ['and', 'or']);
    result[0].should.be.equal("title eq 'something'");
    result[1].should.be.equal("and");
    result[2].should.be.equal("price gt 10");
    result[3].should.be.equal("or");
    result[4].should.be.equal("author eq 'somebody'");
    return done();
  });
});

// ---
// generated by coffee-script 1.9.2
