var bookSchema, conn, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../../.');

support = require('../support');

conn = 'mongodb://localhost/odata-test';

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

describe('hook.put.before', function() {
  it('should work', function(done) {
    var PORT, server;
    PORT = 0;
    server = odata(conn);
    server.resource('book', bookSchema).put().before(function(entity) {
      entity.should.be.have.property('title');
      return done();
    });
    return support(conn, function(books) {
      var s;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return request("http://localhost:" + PORT).put("/book(" + books[0].id + ")").send({
          title: 'new'
        }).end();
      });
    });
  });
  it('should work with multiple hooks', function(done) {
    var PORT, doneTwice, server;
    PORT = 0;
    doneTwice = function() {
      return doneTwice = done;
    };
    server = odata(conn);
    server.resource('book', bookSchema).put().before(function() {
      return doneTwice();
    }).before(function() {
      return doneTwice();
    });
    return support(conn, function(books) {
      var s;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return request("http://localhost:" + PORT).put("/book(" + books[0].id + ")").send({
          title: 'new'
        }).end();
      });
    });
  });
  return it('should save custom modify', function(done) {
    var PORT, server;
    PORT = 0;
    server = odata(conn);
    server.resource('book', bookSchema).put().before(function(entity) {
      return entity.title += 'custom';
    });
    return support(conn, function(books) {
      var s;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return request("http://localhost:" + PORT).put("/book(" + books[0].id + ")").send({
          title: 'new'
        }).end(function() {
          return request("http://localhost:" + PORT).get("/book(" + books[0].id + ")").end(function(err, res) {
            res.body.title.should.be.equal('new' + 'custom');
            return done();
          });
        });
      });
    });
  });
});

// ---
// generated by coffee-script 1.9.2
