var bookSchema, conn, odata, request, should, support;

should = require('should');

request = require('supertest');

odata = require('../../.');

support = require('../support');

conn = 'mongodb://localhost/odata-test';

bookSchema = {
  author: String,
  description: String,
  genre: String,
  price: Number,
  publish_date: Date,
  title: String
};

describe('hook.all.before', function() {
  return it('should work', function(done) {
    var PORT, doneTwice, server;
    PORT = 0;
    doneTwice = function() {
      return doneTwice = done;
    };
    server = odata(conn);
    server.resource('book', bookSchema).all().before(function() {
      return doneTwice();
    });
    return support(conn, function(books) {
      var s;
      return s = server.listen(PORT, function() {
        PORT = s.address().port;
        return request("http://localhost:" + PORT).get("/book(" + books[0].id + ")").end(function() {
          return request("http://localhost:" + PORT).get("/book").end();
        });
      });
    });
  });
});

// ---
// generated by coffee-script 1.9.2
